language: php
php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist
  - php vendor/bin/coveralls -v
